---
title: "Epistemology Vizualized"
---

This is a prototype website for the [*Epistemology Visualized* project](https://github.com/jdutant/ep-viz).

Copyright 2025 Julien Dutant. Distributed under a 
GNU General Public License 3. 

## Aims

The project aims at providing open source, modular, interactive visualizations of important theorms and models in epistemology, starting with political epistemology.

## Example

See the [Condorcet Jury Theorem](topics/condorcet.qmd) page for a prototype.

## Technicalities

* Text: markdown and the occasional LaTeX for maths.
* Code: Javascript for lean and fast in-browser rendering.
* Interactive visualizations: [Observable](https://observablehq.com/), easy to code and beautiful.
* Document rendering: [Quarto](https://quarto.org). Handles website structure, scholarly apparatus, LaTeX and Observable. 

These choices aren't set in stone. I've considered interactive Jupyter notebooks, Observable notebooks. There are yet others.

## GitHub page

Source code available on [jdutant/ep-viz](https://github.com/jdutant/ep-viz) on GitHub.